**Theoretical Questions:**
Q1:
Ans: NumPy is a python libeary for numeric computations and data manipulation in scientific computing and data analysis as it provides multidimesional array, random number generantion, data manipulation.. NumPy is faster due to its implementation in C, it's memory efficiency, and it is easy to use.


Q2:
Ans:
np.mean()
  it is used to calculate arithmetic mean of a array, but doesn't compute weighted averages
np.average()
  it is also used to calculate arithmetic mean but the weighted averages can also be computed.

  we use np.mean() when we need a simple arithmetic mean without any weights

  but we use np.average() when wen need to calculate weighted average


Q3:
Ans:
Reversing NumPy arrays:
 1. using slicing
 2. using np.flip()


Q4:
Ans:
We can determine the data type of elements in a NumPy array by using dtpye attribute ( arr.dtype)
Importance:
 1. Determines the size of each element in bytes.
 2. Using datatype can improve performance.


 Q5:
 ndarrays are the fundamental data structures in NumPy, they represent multidimensional arrays of homogeneous data types.
 Diiference b|w ndarrays and python list:
 1. these are homogenous and lists are hetrogenous
 2. used for fast numerical computations and lists are slower for numerical computations.


 Q6:
 Ans:
 NumPy arrays are more significant then python lists for when dealing with large scale numerical opperations.

 Q7:
 Ans:
1. vstack()
    stacks arrays in row wise sequence.
2. hstack()
    Stacks arrays in colimn wise sequence


 Q8:
 Ans:
 flipr()
  filps the array horizontally

 flipud()
  flips the array verically


  Q9:
  Ans:
  array_split()
   1. splits the array into multiple subarrays .
   2. Handles uneven splits gracefully.

   for uneven splits the extra elemets are distributed to the initial sub array


  Q10:
  Ans:
  Vectorizations:
   Vectorization is the process of performing operations on entire arrays without explicit loops.

  Broadcasting:
   Broadcasting is NumPy's mechanism for performing operations on arrays of different shapes.




In [2]:
# Practical Questions:
#1
import numpy as np
arr = np.random.randint(1, 101, size = (3, 3))
arr.T #(to interchange rows and columns)

array([[22, 33,  2],
       [32, 11, 94],
       [35, 88, 82]])

In [3]:
#2:
arr = np.arange(10)
arr2 = arr.reshape(2,5)
arr3 = arr.reshape(5,2)

In [4]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
arr3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [7]:
#3:
arr = np.random.randn(4, 4)
arr

array([[-0.07755243,  0.31817804, -1.58618108,  2.58902693],
       [-0.20628993, -0.39926306, -0.95648926, -1.02024951],
       [ 1.31893705, -0.42862561,  0.15356882,  1.53001812],
       [ 1.70776474,  0.62242105, -0.44081627, -1.06242754]])

In [8]:
#4:
arr = np.arange(10, 61, 5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [9]:
arr = np.array(['python', 'numpy', 'pandas'])
arr1 = np.char.upper(arr)

In [10]:
arr1

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [11]:
arr2 = np.char.lower(arr)

In [12]:
arr2

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [13]:
arr3 = np.char.title(arr)

In [14]:
arr3

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [15]:
#6:
arr = np.array(['hello', 'my', 'name', 'is', 'navdeep'])
arr1 = np.char.join('', arr)

In [16]:
arr1

array(['hello', 'my', 'name', 'is', 'navdeep'], dtype='<U7')

In [17]:
arr1 = np.random.randint(1, 5, size = (2, 3))
arr2 = np.random.randint(1, 5, size = (2, 3))

In [18]:
arr1

array([[1, 2, 2],
       [3, 2, 2]])

In [19]:
arr2

array([[1, 3, 1],
       [4, 3, 2]])

In [20]:
#addition:
arrA = arr1 + arr2
arrA

array([[2, 5, 3],
       [7, 5, 4]])

In [21]:
arrS = arr1 - arr2
arrS

array([[ 0, -1,  1],
       [-1, -1,  0]])

In [22]:
arrM = arr1 * arr2
arrM

array([[ 1,  6,  2],
       [12,  6,  4]])

In [23]:
arrD = arr1 / arr2
arrD

array([[1.        , 0.66666667, 2.        ],
       [0.75      , 0.66666667, 1.        ]])

In [24]:
#8:
arr1 = np.eye(5)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
arrD = np.diag(arr1)
arrD

array([1., 1., 1., 1., 1.])

In [26]:
#9:
arr1 = np.random.randint(0, 1000, 100)
arr1

array([315, 519, 232, 114, 272, 826, 909, 712, 205, 788, 191, 250, 899,
       271, 294, 410, 388, 756, 538, 712, 984, 656, 966, 986,  25, 697,
       749, 238, 973, 586, 167, 431,   0, 560, 119,  54, 207, 631, 118,
       300, 352, 477,  11,  88, 781, 500, 562, 783, 875, 742, 240, 140,
        99, 160,  20, 434, 282, 739, 753, 786, 942, 107, 871, 246, 596,
       174, 243, 614, 820, 127, 255, 299, 634, 514, 287, 772, 774, 525,
       842, 215, 392, 191, 897, 766, 440, 688, 220, 570,  50, 868, 676,
       839, 537, 726, 467, 537, 764, 347, 306, 662])

In [27]:
def is_prime(num):
  if num <= 3:
    return True
  if num % 2 == 0 or num % 3 == 0:
    return False
  i = 5
  while i * i <= num:
    if num%i == 0 or num % (i +2) == 0:
      return False
    i += 6
    return True

In [28]:
prime_numbers = arr1[np.vectorize(is_prime)(arr1)]
prime_numbers

array([191, 899, 271, 697, 167, 431,   0, 631, 781, 739, 107, 871, 127,
       299, 191, 839, 467, 347])

In [29]:
#10:
daily_temperatures = np.random.randint(20, 40, size=28)

weekly_temperatures = daily_temperatures.reshape(4, 7)

weekly_averages = np.mean(weekly_temperatures, axis=1)

print("Daily temperatures:\n", daily_temperatures)
print("Weekly temperatures:\n", weekly_temperatures)
print("Weekly averages:", weekly_averages)


Daily temperatures:
 [37 24 35 21 29 21 27 32 38 33 26 31 28 22 33 33 34 23 22 38 20 26 25 20
 21 21 38 39]
Weekly temperatures:
 [[37 24 35 21 29 21 27]
 [32 38 33 26 31 28 22]
 [33 33 34 23 22 38 20]
 [26 25 20 21 21 38 39]]
Weekly averages: [27.71428571 30.         29.         27.14285714]
